### ISSUE TITLE
使用您提供的ProxylessBackbone作为骨架网络，效果基本得不到提升，想问一下怎么回事呢

### ISSUE THREAD

**Issue by wuxiaolianggit** [AutoML-4Paradigm/AutoSTR#2]
您好，大神，使用您提供的ProxylessBackbone作为骨架网络，然后接入rnn编码，利用ctc loss训练，效果基本得不到提升，想问一下怎么回事呢？您的这个NAS搜索得到网络和vgg还没有vgg网络精度高，想问一下大佬是什么原因呢

**Comment by wuxiaolianggit** [comment]
您好，大神，使用您提供的ProxylessBackbone作为骨架网络，然后接入rnn编码，利用ctc loss训练，效果基本得不到提升，想问一下怎么回事呢？您的这个NAS搜索得到网络和vgg还没有vgg网络精度高，想问一下大佬是什么原因呢 @quanmingyao @huizhang0110

**Comment by ZhangQihan** [comment]
@wuxiaolianggit 

您好，我也在学习这个project，能否加您的联系方式讨论。（zhangqihanzach@163.com）

**Comment by huizhang0110** [comment]
您好，@wuxiaolianggit 
NAS的优点是针对任务和要求去定制结构。我们在特定的数据集和识别pipeline下找到的backbone，并不一定能直接适用您的数据和模型结构上面，相比于人类专家手工设计的结构，其泛化性确实存在问题。

**Comment by wuxiaolianggit** [comment]
好的，了解了，多谢大神回复 @huizhang0110

**Comment by wuxiaolianggit** [comment]
@ZhangQihan 可以啊，可以以多交流一下
