### ISSUE TITLE
Download of pretrained model from baidu

### ISSUE THREAD

**Issue by bursh-dev** [AutoML-4Paradigm/AutoSTR#3]
Hello,
The  download of pretrained model from baidu is problematic -  it requires registration which is possible only for Chinese phone numbers
Can you suggest alternative source for downloading?
Thanks!

**Comment by huizhang0110** [comment]
Hi, we have uploaded the logs and checkpoints into the [Google drive](https://drive.google.com/file/d/1BhJueZNG09quLqT46p6J7wSbNn84ZNTz/view?usp=sharing).
