### ISSUE TITLE
UserWarning: RNN module weights are not part of single contiguous chunk of memory

### ISSUE THREAD

**Issue by dengxiaolei** [AutoML-4Paradigm/AutoSTR#4]
多卡运行的时候出现：UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().

**Comment by cw-plus** [comment]
Uncomment #self.gru.flatten_parameters() in attention_recognition_head.py

**Comment by huizhang0110** [comment]
Thanks for @chaoyang1994's suggestion but I did not meet such a warning before, maybe due to an inconsistent version.
